In [14]:
import torch
from torch.nn import functional as F

score = torch.randn(2, 3)
prob1 = F.softmax(score, 0) #按列计算
prob2 = F.softmax(score, 1) #按行计算
prob3 = F.softmax(score, -1) #按最后一个维度计算，因此还是按行计算


print(score)

print(prob1)
print(prob2)
print(prob3)


tensor([[ 0.2470, -0.6132, -0.4713],
        [-0.0559,  0.1997,  0.3290]])
tensor([[0.5751, 0.3073, 0.3100],
        [0.4249, 0.6927, 0.6900]])
tensor([[0.5234, 0.2214, 0.2552],
        [0.2659, 0.3433, 0.3907]])
tensor([[0.5234, 0.2214, 0.2552],
        [0.2659, 0.3433, 0.3907]])


In [18]:
# 由于缩放点积注意力机制有个/根号d，这个主要用来控制缩放，防止梯度爆炸
alpha1 = 0.1
alpha2 = 10

acore = torch.randn(5)
prob1 = F.softmax(score*alpha1, -1)
prob2 = F.softmax(score*alpha2, -1)

print(prob1)
print(prob2)

#数学上能够验证QK的方差为根号d，因此除以一个根号d以控制方差，从而控制计算梯度的时候消失or爆炸的问题

tensor([[0.3511, 0.3222, 0.3268],
        [0.3263, 0.3347, 0.3391]])
tensor([[9.9906e-01, 1.8365e-04, 7.5893e-04],
        [1.6446e-02, 2.1176e-01, 7.7179e-01]])
